export type SearchBootstrap = {
  affilationOptions: string[];
  stateOptions: string[];
  schoolScpecialityTypeOptions: string[];
  levelOfSchoolingOptions: string[];
  schoolSubtypeOptions: string[];
  genderOptions: string[];
  selectiveOptions: string[];
  ownershipOptions: string[];
};

export const bootstrap: SearchBootstrap = {
  affilationOptions: [
    "N/A",
    "Anglican",
    "Catholic (Roman)",
    "Non-Denominational",
    "Seventh Day Adventist",
    "Other",
    "Montessori School",
    "Steiner School",
    "Uniting Church",
    "Jewish",
    "Catholic (Other)",
    "Presbyterian",
    "Lutheran",
    "Christian School",
    "Islamic",
    "Baptist",
    "Pentecostal",
    "Hare Krishna",
    "Inter-Denominational",
    "Orthodox, Greek",
    "Ananda Marga",
    "Orthodox, Other",
    "Brethren",
    "Other Religious Affiliation",
  ],
  stateOptions: ["NSW"],
  schoolScpecialityTypeOptions: [
    "Comprehensive",
    "Language",
    "Agricultural",
    "Senior College",
    "Performing Arts",
    "Sports",
    "Intensive English",
    "Technology",
    "Junior College",
    "Visual Arts",
    "Creative Arts",
    "Marine Technology",
    "Distance Education",
    "Rural Technology",
    "Other",
    "Non special",
    "Special",
  ],
  levelOfSchoolingOptions: [
    "Primary School",
    "Other School",
    "Secondary School",
    "Infants School",
    "Schools for Specific Purposes",
    "Environmental Education Centre",
    "Central/Community School",
    "Combined",
    "Primary",
    "Secondary",
    "Special",
  ],
  schoolSubtypeOptions: [
    "Kindergarten to Year 6",
    "Nursery school (similar to a Pre school)",
    "Year 7 to Year 12",
    "Year 11 to Year 12",
    "Year 10 to Year 12",
    "Kindergarten to Year 2",
    "Emotional disturbance",
    "Environmental Education Centre (formerly Field Studies Centres)",
    "Juvenile Justice establishment",
    "Behaviour Disorder",
    "Diagnostic remedial reading assesment",
    "Debilitated by physical difficulties",
    "Hospital School",
    "Medium / High Support needs",
    "Kindergarten to Year 12",
    "Intensive English Centre",
    "Year 7 to Year 10",
    "Year 7 to Year 9",
    "N/A",
  ],
  genderOptions: ["COED", "BOYS", "GIRLS"],
  selectiveOptions: ["NOT_SELECTIVE", "PARTLY_SELECTIVE", "FULLY_SELECTIVE"],
  ownershipOptions: ["Government", "Non Government"],
};
